// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryManagement.Infrastructure.Persistence.Repositories;

#nullable disable

namespace SalaryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(SalaryManagementContext))]
    partial class SalaryManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Admin", b =>
                {
                    b.Property<string>("AdminId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("admin_id");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<bool?>("IsFirstLogin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_first_login");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("AdminId")
                        .HasName("PRIMARY");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.HasKey("CompanyId")
                        .HasName("PRIMARY");

                    b.ToTable("companys", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Contract", b =>
                {
                    b.Property<string>("ContractId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contract_id");

                    b.Property<double?>("BasicSalary")
                        .HasColumnType("double")
                        .HasColumnName("basic_salary");

                    b.Property<double?>("Bhtn")
                        .HasColumnType("double");

                    b.Property<double?>("Bhxh")
                        .HasColumnType("double")
                        .HasColumnName("bhxh");

                    b.Property<double?>("Bhyt")
                        .HasColumnType("double");

                    b.Property<string>("ContractStatus")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContractType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("File")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file");

                    b.Property<string>("Job")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("job");

                    b.Property<string>("PartnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("partner_id");

                    b.Property<double?>("PartnerPrice")
                        .HasColumnType("double")
                        .HasColumnName("partner_price");

                    b.Property<string>("SalaryType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<double?>("Tax")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("date");

                    b.HasKey("ContractId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmployeeId" }, "employee_id");

                    b.HasIndex(new[] { "PartnerId" }, "partner_id");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.ContractStatus", b =>
                {
                    b.Property<string>("ContractStatusId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contract_status_id");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDeleted");

                    b.Property<string>("StatusName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status_name");

                    b.HasKey("ContractStatusId")
                        .HasName("PRIMARY");

                    b.ToTable("contract_status", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.ContractType", b =>
                {
                    b.Property<string>("ContractTypeId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contract_type_id");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDeleted");

                    b.Property<string>("TypeName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("type_name");

                    b.HasKey("ContractTypeId")
                        .HasName("PRIMARY");

                    b.ToTable("contract_types", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("employee_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int?>("IdentifyNumber")
                        .HasColumnType("int")
                        .HasColumnName("identify_number");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("EmployeeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique();

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Holiday", b =>
                {
                    b.Property<string>("HolidayId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("holiday_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("HolidayName")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDeleted");

                    b.Property<bool?>("IsPaid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isPaid");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("HolidayId")
                        .HasName("PRIMARY");

                    b.ToTable("holidays", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.LeaveLog", b =>
                {
                    b.Property<string>("LeaveTimeId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("leave_time_id");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("date")
                        .HasColumnName("leave_date");

                    b.Property<int?>("LeaveHours")
                        .HasColumnType("int")
                        .HasColumnName("leave_hours");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.HasKey("LeaveTimeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmployeeId" }, "employee_id")
                        .HasDatabaseName("employee_id1");

                    b.ToTable("leave_logs", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.OvertimeLog", b =>
                {
                    b.Property<string>("OvertimeId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("overtime_id");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("employee_id");

                    b.Property<int?>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("hours");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime?>("OvertimeDay")
                        .HasColumnType("date")
                        .HasColumnName("overtime_day");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.HasKey("OvertimeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmployeeId" }, "employee_id")
                        .HasDatabaseName("employee_id2");

                    b.ToTable("overtime_logs", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.PaidHistory", b =>
                {
                    b.Property<string>("PayHistoryId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pay_history_id");

                    b.Property<double?>("AccidentInsurance")
                        .HasColumnType("double")
                        .HasColumnName("accident_insurance");

                    b.Property<double?>("BaseSalary")
                        .HasColumnType("double")
                        .HasColumnName("base_salary");

                    b.Property<double?>("Bonus")
                        .HasColumnType("double")
                        .HasColumnName("bonus");

                    b.Property<string>("ContractId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contract_id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("create_at");

                    b.Property<double?>("Deductions")
                        .HasColumnType("double")
                        .HasColumnName("deductions");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("date")
                        .HasColumnName("deleted_at");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("employee_id");

                    b.Property<double?>("HealthInsurance")
                        .HasColumnType("double")
                        .HasColumnName("health_insurance");

                    b.Property<int?>("LeaveHours")
                        .HasColumnType("int")
                        .HasColumnName("leave_hours");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int?>("OtHours")
                        .HasColumnType("int")
                        .HasColumnName("ot_hours");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("date")
                        .HasColumnName("paid_date");

                    b.Property<string>("PaidType")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("paid_type");

                    b.Property<DateTime?>("PayrollPeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("payroll_period_end");

                    b.Property<DateTime?>("PayrollPeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("payroll_period_start");

                    b.Property<double?>("SalaryAmount")
                        .HasColumnType("double")
                        .HasColumnName("salary_amount");

                    b.Property<double?>("SocialInsurance")
                        .HasColumnType("double")
                        .HasColumnName("social_insurance");

                    b.Property<int?>("StandardWorkHours")
                        .HasColumnType("int")
                        .HasColumnName("standard_work_hours");

                    b.Property<double?>("Tax")
                        .HasColumnType("double")
                        .HasColumnName("tax");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("date")
                        .HasColumnName("update_at");

                    b.Property<int?>("WorkHours")
                        .HasColumnType("int")
                        .HasColumnName("work_hours");

                    b.HasKey("PayHistoryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ContractId" }, "contract_id");

                    b.HasIndex(new[] { "EmployeeId" }, "employee_id")
                        .HasDatabaseName("employee_id3");

                    b.HasIndex(new[] { "PaidDate", "PaidType", "DeletedAt" }, "optimize_query");

                    b.ToTable("paid_history", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Payroll", b =>
                {
                    b.Property<string>("PayrollId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("payroll_id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("employee_id");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<double?>("Tax")
                        .HasColumnType("double")
                        .HasColumnName("tax");

                    b.Property<double?>("Total")
                        .HasColumnType("double")
                        .HasColumnName("total");

                    b.Property<double?>("TotalBonus")
                        .HasColumnType("double")
                        .HasColumnName("total_bonus");

                    b.Property<double?>("TotalDeduction")
                        .HasColumnType("double")
                        .HasColumnName("total_deduction");

                    b.HasKey("PayrollId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmployeeId" }, "employee_id")
                        .HasDatabaseName("employee_id4");

                    b.ToTable("payrolls", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.SalaryType", b =>
                {
                    b.Property<string>("SalaryTypeId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("salary_type_id");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isDeleted");

                    b.Property<string>("SalaryTypeName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("salary_type_name");

                    b.HasKey("SalaryTypeId")
                        .HasName("PRIMARY");

                    b.ToTable("salary_types", (string)null);
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Contract", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("Contracts")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("contracts_ibfk_1");

                    b.HasOne("SalaryManagement.Domain.Entities.Company", "Partner")
                        .WithMany("Contracts")
                        .HasForeignKey("PartnerId")
                        .IsRequired()
                        .HasConstraintName("contracts_ibfk_5");

                    b.Navigation("Employee");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.LeaveLog", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("LeaveLogs")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("leave_logs_ibfk_1");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.OvertimeLog", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("OvertimeLogs")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("overtime_logs_ibfk_1");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.PaidHistory", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.Contract", "Contract")
                        .WithMany("PaidHistories")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("paid_history_ibfk_2");

                    b.HasOne("SalaryManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("PaidHistories")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("paid_history_ibfk_1");

                    b.Navigation("Contract");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Payroll", b =>
                {
                    b.HasOne("SalaryManagement.Domain.Entities.Employee", "Employee")
                        .WithMany("Payrolls")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("payrolls_ibfk_1");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Company", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Contract", b =>
                {
                    b.Navigation("PaidHistories");
                });

            modelBuilder.Entity("SalaryManagement.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("LeaveLogs");

                    b.Navigation("OvertimeLogs");

                    b.Navigation("PaidHistories");

                    b.Navigation("Payrolls");
                });
#pragma warning restore 612, 618
        }
    }
}
